// react-chat/src/pages/Chat.js
import * as React from "react";
import styled from "styled-components";

import Template from "../components/template";
import ChatContainer from "../components/services/chat/chat.container";

export default class Chat extends React.Component {
  componentWillMount() {
    console.log("componentWillMount");
    const user = sessionStorage.getItem("user");
    if (!JSON.parse(user).uid) {
      this.props.history.push("/");
    }
  }

  render() {
    return (
      <Template>
        <Container>
          <ChatContainer />
        </Container>
      </Template>
    );
  }
}

const Container = styled.div`
  width: 70%;
  margin: 0 auto;
`;

// vue-chat/src/views/Chat.vue
<template>
  <div class="chat">
    <ChatContainer />
  </div>
</template>

<script>
import firebase from "firebase";
import ChatContainer from "@/components/services/Chat/Chat.container";

export default {
  name: "Chat",
  components: { ChatContainer },
  created() {
    firebase.auth().onAuthStateChanged(async user => {
      if (!user) {
        this.$router.push("/");
        return;
      }
      await this.$store.dispatch("setUser", user);
    });
  }
};
</script>

<style lang="scss" scoped>
.chat {
  width: 70%;
  margin: 0 auto;
}
</style>
