// react-chat/src/pages/Login.js
import * as React from "react";
import firebase from "firebase";
import styled from "styled-components";

import Template from "../components/template";
import SignImage from "../assets/images/google_signin.png";

export default class Login extends React.Component {
  onEnter() {
    const provider = new firebase.auth.GoogleAuthProvider();

    firebase
      .auth()
      .signInWithPopup(provider)
      .then((result) => {
        sessionStorage.setItem("uid", result.user.uid);
        this.props.history.push("/chat");
      })
      .catch((e) => {
        console.log("login error: ", e);
      });
  }

  render() {
    return (
      <Template>
        <Container>
          <SignImg
            onClick={this.onEnter.bind(this)}
            src={SignImage}
            alt="Google Signin"
          />
        </Container>
      </Template>
    );
  }
}

const Container = styled.div``;
const SignImg = styled.img`
  margin: 0 auto;
  cursor: pointer;
`;

// vue-chat/src/views/Login.vue
<template>
  <div class="login">
    <img
      @click="onEnter"
      alt="Google Signin"
      src="../assets/images/google_signin.png"
    />
  </div>
</template>

<script>
import firebase from "firebase";

export default {
  name: "Login",
  methods: {
    onEnter() {
      const provider = new firebase.auth.GoogleAuthProvider();

      firebase
        .auth()
        .signInWithPopup(provider)
        .then(async result => {
          await this.$store.dispatch("setUser", result.user);
          this.$router.push("/chat");
        })
        .catch(e => {
          console.log("login error: ", e);
        });
    }
  }
};
</script>

<style lang="scss" scoped>
.login {
  img {
    margin: 0 auto;
    cursor: pointer;
  }
}
</style>
