// vue-chat/src/components/services/Chat/Chat.container.vue
<template>
  <Chat :messages="state.messages" :onSend="onSend" />
</template>

<script>
import firebase from "firebase";
import { reactive } from "vue";
import { db } from "@/plugins/firebase";
import Chat from "./Chat";

export default {
  name: "ChatContainer",
  components: { Chat },
  setup() {
    const state = reactive({
      messages: []
    });

    function setMessages(data, msg) {
      if (!data || !msg) return;
      this.state.messages.push({
        id: data?.id,
        name: msg?.name,
        message: msg?.message,
        image: msg?.image
      });
    }

    return {
      state,
      setMessages
    };
  },
  created() {
    const comments = db
      .collection("messages")
      .orderBy("createdAt")
      .limit(10);

    comments.onSnapshot(querySnapshot => {
      querySnapshot.docChanges().forEach(msg => {
        if (msg.type === "added") {
          this.setMessages(msg.doc, msg.doc.data?.());
        }
      });
    });
  },
  methods: {
    onSend(v) {
      const user = this.$store.state.user;
      const comments = db.collection("messages");
      if (user.uid && v.length > 0) {
        comments.add({
          message: v,
          name: user.displayName,
          image: user.photoURL,
          createdAt: new Date()
        });
      }
    },
    logout() {
      firebase.auth().signOut();
    }
  }
};
</script>

// react-chat/src/components/services/chat/chat.container.js
import React, { useState, useEffect } from "react";

import { db } from "../../../plugins/firebase";
import Chat from "./chat";

const ChatContainer = () => {
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    console.log("useEffect");
    const comments = db.collection("messages").orderBy("createdAt").limit(10);
    let newMessages = [];

    comments.onSnapshot((querySnapshot) => {
      querySnapshot.docChanges().forEach((msg) => {
        if (msg.type === "added") {
          newMessages.push({
            id: msg.doc?.id,
            name: msg.doc.data?.()?.name,
            message: msg.doc.data?.()?.message,
            image: msg.doc.data?.()?.image,
          });
        }
        setMessages(messages.concat(newMessages));
      });
    });
  }, []);

  const onSend = (v) => {
    const user = sessionStorage.getItem("user");
    const parseUser = JSON.parse(user);
    const comments = db.collection("messages");

    if (parseUser.uid && v.length > 0) {
      comments.add({
        message: v,
        name: parseUser.name,
        image: parseUser.photo,
        createdAt: new Date(),
      });
    }
  };

  return <Chat messages={messages} onSend={onSend} />;
};

export default ChatContainer;
